dpi-aware=no
font=FiraMono-rerular:size=14
icon-theme=Papirus-Dark
prompt="❯  "
width=45
fields=name,generic,comment,categories,filename,keywords
terminal=foot -e
show-actions=yes
exit-on-keyboard-focus-loss=no

[colors]
background=08052bdd
text=e3e3eaff
prompt=ff7f7fff
# placeholder=ffd966ff
input=ff7f7fff
match=FFE57Fff
selection-match=ffe57fff
selection=44475add
selection-text=ffffffff
# counter=93a1a1ff
border=7f3fbf55
