[main]
shell=/bin/zsh
include=/usr/share/foot/themes/catppuccin-macchiato
#font=0xProtoNerdFontMono-Regular:size=12
font=FiraCode Nerd Font Mono:size=12
font-bold=FiraCode Nerd Font Mono:weight=bold:size=12
font-italic=FiraCode Nerd Font Mono:slant=italic:size=12
dpi-aware=yes
initial-window-size-chars=70x17
pad=10x10
title=foot

[scrollback]
lines=10000

[csd]
preferred=none #Completely disable built-in decorations (title and frames)
#border-width=1
#border-color=42BDF8

[colors-dark]
selection-foreground=c0caf5
selection-background=33467c

[cursor]
style=block
blink=yes

[key-bindings]
#fullscreen=Alt+Shift+Return
maximize=Alt+Shift+Return

[url]
launch=xdg-open ${url}
osc8-underline=url-mode
style=dotted
# URL Mode: Start with Ctrl+Shift+U
# Highlite URL Ctrl+Shift+O
